version: '3'

services:

  # celery
  celery:
    build: .
    command: celery -A main worker --loglevel=info 
    volumes:
      - ./app:/app

  flower:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 5555:5555
    command: sh -c "sleep 2 && celery -A main flower"
    depends_on:
      - celery
